#version 450

#define buffer_ld4(buf,i) buf[i]
#define buffer_st4(buf,i,v) {buf[i]=v;}

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

layout (constant_id = 0) const int loop = 1;
layout (binding = 0) buffer a_blob { vec4 a_blob_data[]; };
layout (binding = 1) buffer b_blob { vec4 b_blob_data[]; };
layout (binding = 2) writeonly buffer c_blob { vec4 c_blob_data[]; };

void main() {

    const int gx = int(gl_GlobalInvocationID.x);
    vec4 a = buffer_ld4(a_blob_data, gx);
    vec4 b = buffer_ld4(b_blob_data, gx);
    vec4 c = vec4(1.f);
    for (int i = 0; i < loop; i++)
    {
        c = a * c + b;
        c = a * c + b;
        c = a * c + b;
        c = a * c + b;
        c = a * c + b;
        c = a * c + b;
        c = a * c + b;
        c = a * c + b;
        c = a * c + b;
        c = a * c + b;
        c = a * c + b;
        c = a * c + b;
        c = a * c + b;
        c = a * c + b;
        c = a * c + b;
        c = a * c + b;
    }
    buffer_st4(a_blob_data, gx, a);
    buffer_st4(b_blob_data, gx, b);
    buffer_st4(c_blob_data, gx, c);
}