#version 450

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0) buffer inBuffer {
    float inData[];
};

layout(binding = 1) buffer outBuffer {
    float outData[];
};

void main() {

    uint index = gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * gl_NumWorkGroups.x + gl_GlobalInvocationID.z * gl_NumWorkGroups.x * gl_NumWorkGroups.y;

    float inValue = inData[index];
    outData[index] = inValue + 1.f;
}