#version 450

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std140, binding = 0) buffer input1Buffer {
    vec4 input1Data[];
};

layout(std140, binding = 1) buffer input2Buffer {
    vec4 input2Data[];
};

layout(std140, binding = 2) buffer output1Buffer {
    vec4 output1Data[];
};

void main() {

    uint index = gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * gl_NumWorkGroups.x + gl_GlobalInvocationID.z * gl_NumWorkGroups.x * gl_NumWorkGroups.y;

    vec4 in1 = input1Data[index];
    vec4 in2 = input2Data[index];
    output1Data[index] = in1 + in2;
}